name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cake Action
      uses: ecampidoglio/cake-action@v1.1.1
      with:
        # The path of the Cake script to run.
        script-path: build.cake
        # The name of the task to execute. Note that this argument must be supported by the script.
        target: Publish
        # The verbosity level with which to run the script. Valid values are: Quiet, Minimal, Normal, Verbose or Diagnostic.
        verbosity: Verbose                
